<?php
/**
 * Created by PhpStorm.
 * User: HULANG-BTB
 * Date: 2019/3/10
 * Time: 21:27
 */

namespace app\index\controller;

use think\Controller;
use think\Exception;
use think\Db;
use think\facade\Request;
use think\facade\Config;
use think\facade\Validate;

class Donation extends Base
{
    private $AlipayUrl = "https://qr.alipay.com/fkx08963tuknz1ixda6hqfc";

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        // parent::index(); // TODO: Change the autogenerated stub
        $UserAgent = $this->request->server('HTTP_USER_AGENT');
        if ( strpos( $UserAgent,'AlipayClient') !==false ){
            return $this->redirect($this->AlipayUrl);
        }
        if ( strpos( $UserAgent,'MicroMessenger') !==false ){
            return $this->fetch('wx');
        }
        if ( strpos( $UserAgent,'QQ') !==false ){
            return $this->fetch('qq');
        }
        return $this->redirect('index/index/index');
    }
}