<?php
/**
 * Created by PhpStorm.
 * User: HULANG-BTB
 * Date: 2019/3/10
 * Time: 16:08
 */

namespace app\index\controller;

use think\Controller;
use think\Exception;
use think\Db;
use think\facade\Request;
use think\facade\Config;
use think\facade\Validate;

class Tag extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
        $id = $this->request->param('id/d', 0);
        $page = $this->request->param('page/d', 1);

        $tags = Db::name("tags")
            ->select();
        $this->assign("tags", $tags);

        $view_rank = Db::name('articles')
            ->order(['view_count' => 'desc'])
            ->where(['status' => 0])
            ->limit(5)
            ->select();
        $this->assign("view", $view_rank);

        $tagExist = Db::name('tags')
            ->where(['id' => $id])
            ->count();
        if (!$tagExist)
        {
            return $this->error('非法操作！');
        }

        $articles = Db::name('articles a')
            ->order(['top' => 'desc', 'create_at' => 'desc', 'view_count' => 'desc', 'comment_count' => 'desc'])
            ->where(['status' => 0])
            ->where('a.tags_list', 'like', '%'.$id.'%')
            ->join('category c', 'a.category_id = c.id')
            ->field(['a.id' => 'id', 'a.title' => 'title', 'a.abstract' => 'abstract', 'a.content' => 'content', 'a.username' => 'username', 'a.comment_count' => 'comment_count', 'a.view_count' => 'view_count', 'a.create_at' => 'create_at', 'c.name' => 'category', 'a.thumbnail' => 'thumbnail'])
            ->page($page, Config::get('paginate.list_rows'))
            ->select();

        $count = Db::name('articles')
            ->where(['status' => 0])
            ->where('tags_list', 'like', '%'.$id.'%')
            ->count();

        $this->assign('articles', $articles);

        $pageInfo = [
            'curr' => $page,
            'all' => ceil($count / Config::get('paginate.list_rows')),
        ];

        $this->assign('page', $pageInfo);

        return $this->fetch();
    }


}